#!/usr/bin/env bash
# --------------------------------------------------------
# Author: glender
# --------------------------------------------------------

OPTION=0
QUICK=0
IO_FILE="$PWD/ips.txt"
declare -a pids
MAX_PARALLEL=10
MAX_SLEEP=5.0
WORDLIST=""

install()
{
	if [ "$EUID" -ne 0 ]; then
		echo "NOT installing infGather!"
		echo "NOT installing infGather bash complete!"
		echo "NOT installing infGather man page!"
		return 1
	fi

	IG="/usr/bin/infGather"
	BC="/$USER/.bash_completion.d/"
	MAN="/usr/share/man/man1"

	echo "Installing infGather!"
	file=$(find /$USER/ -name infGather)
	cp -f $file $IG > /dev/null 2>&1

	echo "Installing infGather bash complete!"
	mkdir -p $BC
	file=$(find /$USER/ -name infGather_bc)
	base=$(basename $file)
	cp -f $file $BC > /dev/null 2>&1
	# append sourcing our bash completion file on shell startup
	grep -q -F ". '$BC'/infGather_bc" ~/.bashrc || echo ". '$BC'/infGather_bc" >> /$USER/.bashrc

	echo "Installing infGather man page!"
	mkdir -p $MAN
	file=$(find /$USER/ -name infGather.1)
	cp -f $file $MAN/ > /dev/null 2>&1
	gzip -f $MAN/infGather.1
	# update man pages
	mandb > /dev/null 2>&1
	# make sure that our bash completion takes place
	exec bash
	exit 0
}

check_outfile()
{
	if [[ -f $IO_FILE && -s $IO_FILE ]]; then
		# clear the file
		> "${IO_FILE}"
	else
		touch "${IO_FILE}"
	fi
}

check_installs()
{
	if [ ! type nmap &> /dev/null ]; then
		echo "Please install nmap before you can proceed."
		exit 0
	fi

	if [ ! type enum4linux &> /dev/null ]; then
		echo "Please install enum4linux before you can proceed."
		exit 0
	fi
	
	if [ ! type nikto &> /dev/null ]; then
		echo "Please install nikto before you can proceed."
		exit 0
	fi

	if [ ! type dirb &> /dev/null ]; then
		echo "Please install dirb before you can proceed."
		exit 0
	fi
}

display_banner()
{
	echo ""
	echo ""
 	echo "###                #####                                    "
 	echo " #  #    # ###### #     #   ##   ##### #    # ###### #####  "
 	echo " #  ##   # #      #        #  #    #   #    # #      #    # "
 	echo " #  # #  # #####  #  #### #    #   #   ###### #####  #    # "
 	echo " #  #  # # #      #     # ######   #   #    # #      #####  "
 	echo " #  #   ## #      #     # #    #   #   #    # #      #   #  "
 	echo "### #    # #       #####  #    #   #   #    # ###### #    # "
 	echo ""
 	echo ""
	echo "Author: glender"
	echo "https://github.com/glender/InfGather"
	echo ""
	echo ""
}

display_usage()
{
	echo "Usage: ${0} [options...]"
	echo ""
        echo "		-f, --file		Read a file of IPs instead of scanning for alive boxes"
        echo "		-h, --help		Help information"
	echo "	[**]	-i, --ip		The IP triple to scan or the full IP to scan (i.e. 10.11.1 OR 10.11.1.1)"
	echo "		-m, --max		Maximum parallel processes to run (Default is set to $MAX_PARALLEL)"
	echo "		-p, --perm		Install infGather so that it can be run from anywhere. Install man page and bash completion"
	echo "		-q, --quick		Skip the heavier nmap scans"
	echo "		-s, --single		Scan a single IP address"
	echo "		-w, --wlist		Wordlist to use (Default will be infGatherWordList.txt)"
	echo "		-z, --ztime		Maximum sleep time between checking if PID completed (Default is set to $MAX_SLEEP s)"
	echo ""
	echo "	[**] is required to run the script"
	echo ""
}

check_ip()
{
	local ip=$1
	local split=(${ip//./ })

	# is the passed in arg of the format ###.###.###?
	if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
		# is each number less than or equal to 255?
		if [[ ${split[0]} -le 255 && ${split[1]} -le 255 && ${split[2]} -le 255 ]]; then
			echo -e "You provided a correct IP... \nMoving on... \n\n"
		else 
			echo -e "Incorrect IP! \nYour IP was out of range! \n\n"
			exit 0
		fi
	fi
}

check_ip_full()
{
	local ip=$1
	local split=(${ip//./ })

	# is the passed in arg of the format ###.###.###?
	if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
		# is each number less than or equal to 255?
		if [[ ${split[0]} -le 255 && ${split[1]} -le 255 && ${split[2]} -le 255 && ${split[3]} -le 255 ]]; then
			echo -e "You provided a correct IP... \nMoving on... \n\n"
			return 0
		else 
			echo -e "Incorrect IP! \nYour IP was out of range! \n\n"
			return 1
		fi
	fi
}

ping_sweep()
{
	check_outfile
	# iterate from 1..255
	for i in `seq 1 255`; do
		# ping to see if it is alive, save into temporary file
		ping -c 1 $1.$i | grep "bytes from" | cut -d " " -f 4 | cut -d ":" -f 1 >> $IO_FILE &
	done
}

check_running()
{
	while [ ${#pids[@]} -ge $MAX_PARALLEL ]; do
		for PID in "${pids[@]}"; do
			if [ -e /proc/${PID} ]; then
				# PID is still running
				continue
			else
				# the PID is no longer running, remove it
				delete=( $PID )
    				if [[ ${pids[PID]} = "${delete[0]}" ]]; then
      					unset 'pids[PID]'
    				fi

			fi
		done
	done
}

wait_for_completion()
{
	echo "Waiting for completion..."

	totalRunning=$(ps -C nmap -C nikto -C dirb -C enum4linux --no-headers | wc -l)

	sp="/-\|"
	i=1
	echo -n ' '
	until [ $totalRunning -eq 1 ] || [ ${#pids[@]} -eq 1 ]; do
		printf "\b${sp:i++%${#sp}:1}"
		sleep $MAX_SLEEP
		totalRunning=$(ps -C nmap -C nikto -C dirb --no-headers | wc -l)
	done

	reset

	# notify the user that we have completed 
	if [ ! type zenity &> /dev/null ]; then
		if [ type xmessage &> /dev/null ]; then
			xmessage -center 'message:$0 has completed. Please check your output.' 
		fi
	else
		echo 'Completed. Please check your output.' | zenity --notification --listen
	fi
}

scans()
{
	location="/$USER/Gather/nmap/$1"
	mkdir -p $location

	today=`date '+%Y_%m_%d__%H_%M_%S'`
	nmap -Pn -sn -T4 -oN "$location/$1.$today.nmapHostDiscovery" $1 > /dev/null &
	pids[$!]=$!
	check_running 

	nmap -Pn -sU -p 53 -sV -P0 --script dns-recursion -oN "$location/$1.$today.nmapDNSRecursion" $1 > /dev/null &
	pids[$!]=$!
	check_running 

	if [ $QUICK -eq 0 ]; then
		nmap -Pn -p- -A -oN "$location/$1.$today.nmapAllOpenPorts" $1 -r -n --open > /dev/null &
		pids[$!]=$!
		check_running
		nmap -Pn -T4 -sU -oN "$location/$1.$today.nmapUDPScan" $1 > /dev/null &
		pids[$!]=$!
		check_running
	fi	

	nmap -Pn -vv --script vuln -oN "$location/$1.$today.nmapVulnScan" $1 > /dev/null &
	pids[$!]=$!
	check_running

	nmap -Pn -sV -T4 -vv -oN "$location/$1.$today.nmapServiceDiscovery" $1 > /dev/null &
	pids[$!]=$!
	check_running

	nikto_scan $! $location $1 &
	pids[$!]=$!
	check_running

	nmap -Pn -T4 -sS -p139,445 --script=smb-enum-users -oN "$location/$1.$today.nmapSmbEnumUsers" $1 > /dev/null &
	pids[$!]=$!
	check_running
	
	nmap -Pn -T4 -sS -p139,445 --script=smb-enum-groups -oN "$location/$1.$today.nmapSmbEnumGroups" $1 > /dev/null &
	pids[$!]=$!
	check_running
	
	nmap -Pn -T4 -sS -p139,445 --script=smb-enum-shares -oN "$location/$1.$today.nmapSmbEnumShares" $1 > /dev/null & 
	pids[$!]=$!
	check_running

	dirb_scan $1 80 "0" &
	pids[$!]=$!
	check_running

	dirb_scan $1 443 "1" &
	pids[$!]=$!
	check_running

	enumlocation="/$USER/Gather/enum4linux/$1"
	mkdir -p $enumlocation
	enum4linux -U -o $1 > $enumlocation/$1.enum4linux 2>&1 &
	pids[$!]=$!
	check_running

}

nikto_scan()
{
	location="/$USER/Gather/nikto/$3"
	mkdir -p $location

	# wait for our main nmap scan to complete, our service detection
	while [ -e /proc/$1 ]; do
		sleep $MAX_SLEEP
	done

	# get ports other than the normal HTTP (80) and HTTPS (443) 
	httpPorts=$(grep -i http $2/*nmap* | grep open | grep -v "80/" | grep -v "443/" | awk -F: '{ print $2 }' | awk -F/ '{ print $1 }')
	
	# get the HTTPS ports
	httpsPorts=$(grep -i http $2/*nmap* | grep open | grep ssl | grep -v "80/" | grep -v "443/" | awk -F: '{ print $2 }' | awk -F/ '{ print $1 }')
	httpsPorts+=$(grep -i https $2/*nmap* | grep open | grep -v "80/" | grep -v "443/" | awk -F: '{ print $2 }' | awk -F/ '{ print $1 }')

	# ensure that they are unique entries
	httpPorts=($(echo "${httpPorts[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
	httpsPorts=($(echo "${httpsPorts[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

	# check the normal HTTPS port for our host
	nmap -p443 $3 -oG - | nikto -h - -output $location/nikto_https_$3.html > /dev/null &
	pids[$!]=$!
	check_running
	
	# check the normal HTTP port for our host
	nmap -p80 $3 -oG - | nikto -h - -output $location/nikto_http_$3.html > /dev/null &
	pids[$!]=$!
	check_running

	# remove the https ports from our http ports
	for target in "${httpsPorts[@]}"; do
  		for i in "${!httpPorts[@]}"; do
    			if [[ ${httpPorts[i]} = "${httpsPorts[0]}" ]]; then
      				unset 'httpPorts[i]'
    			fi
  		done
	done

	# process the https ports that we have found
	for port in "${httpsPorts[@]}"; do
		nikto -host $3 -port $port -ssl -output $location/nikto_https_$3_$port.html > /dev/null &
		pids[$!]=$!
		check_running
		dirb_scan $3 $port "0" &
		pids[$!]=$!
		check_running
	done

	# process the http ports that we have found
	for port in "${httpPorts[@]}"; do
		nikto -host $3 -port $port -output $location/nikto_http_$3_$port.html > /dev/null &
		pids[$!]=$!
		check_running
		dirb_scan $3 $port "1" &
		pids[$!]=$!
		check_running
	done

}

dirb_scan()
{
	# change the max parallel so that dirb does not begin to spawn the $MAX_PARALLEL allowed
	MAX_PARALLEL=$(($MAX_PARALLEL / 2))

	location="/$USER/Gather/dirb/$1"
	mkdir -p $location

	# did the user supply a wordlist?
	if [ "$WORDLIST" == "" ]; then
		WORDLIST=$(find /$USER/ -name infGatherWordList.txt)
		# InfGather wordlist installed?
		if [ "$WORDLIST" == "" ]; then
			echo "Please install the InfGather wordlist, $USER."
			exit 0
		fi

	else
		# does the wordlist exist?
		if [ ! -f $WORDLIST ]; then
			echo "You supplied a wordlist that does not exist...shame on you!"
			exit 0
		fi
	fi

	# get the file size so that we can determine if we need to split into more than one file 
	filesize=$(stat -c%s $WORDLIST)
	base=$(dirname $WORDLIST) 
	fname=$(basename $WORDLIST)
	# half megabyte
	maxSize=500000 
	# newly created filename prefix
	prefix="qwaszx"
	created=0

	# generate random 32 character alphanumeric string
	newDir=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

	if (( filesize > maxSize )); then
		# split the file into parts
		pushd . > /dev/null
		mkdir $base/$newDir
		cd $base 
		split -l 5000 $fname $newDir/$prefix
		popd > /dev/null
	fi

	files=$(shopt -s nullglob dotglob; echo $base/$newDir/*)

	if [[ ${files[@]} =~ $prefix ]]; then
		files=( "${files[@]/$fname}" )
		files=( "${files[@]/$base}" )
		created=1
	fi

	if [ $created -eq 1 ]; then

		# iterate through our smaller files
		for f in $files; do
			bname=$(basename $f)

			if [[ $f =~ $prefix ]]; then
				# HTTP (0) or HTTPS (1)
				if [ "$3" -eq "0" ]; then
					dirb -z 250 http://$1:$2/ $f -o $location/dirb_http_$2.txt -w > $location/dirb_http_$1_$2_$bname.txt &
					pids[$!]=$!
					check_running
				else
					dirb -z 250 https://$1:$2/ $f -o $location/dirb_https_$2.txt -w > $location/dirb_httpd_$1_$2_$bname.txt &
					pids[$!]=$!
					check_running
				fi
			fi

		done

		# cleanup our newly created smaller files
		rm -rf $base/$newDir

	else

		# HTTP (0) or HTTPS (1)
		if [ "$3" -eq "0" ]; then
			dirb http://$1:$2/ $WORDLIST -o $location/dirb_http_$2.txt -w > $location/dirb_http_$1_$2.txt &
			pids[$!]=$!
			check_running
		else
			dirb https://$1:$2/ $WORDLIST -o $location/dirb_https_$2.txt -w > $location/dirb_httpd_$1_$2.txt &
			pids[$!]=$!
			check_running
		fi
	fi

}

read_file_and_scan()
{
	cat $IO_FILE | while read ip; do
		# is the IP address proper?
		check_ip_full $IP
		if [ $? -eq 0 ]; then
			scans $ip
		fi
	done
}

# display banner
display_banner

# check to make sure the user has the proper programs installed 
check_installs

# Get the command line options
for (( i=1; i<=$#; i++)); do
	case "${!i}" in
		# file to read IPs from
		-f|--file)
			arg=$((i+1))
			IO_FILE="${!arg}"
			OPTION=1
			shift # past - option
			;;
		# IP address to sweep
		-i|--ip)
			arg=$((i+1))
			IP="${!arg}"
			OPTION=2
			shift # past - option
			;;
		# single IP address scan
		-s|--single)
			arg=$((i+1))
			IP="${!arg}"
			OPTION=3
			shift # past - option
			;;
		# set maximum parallel processes
		-m|--max)
			arg=$((i+1))
			MAX_PARALLEL="${!arg}"
			shift # past - option
			;;
		# install infGather
		-p|--perm)
			install
			exit 0
			;;
		# install infGather
		-q|--quick)
			QUICK=1
			;;
		# set the maximum sleep time between checking PID completion
		-z|--ztime)
			arg=$((i+1))
			MAX_SLEEP="${!arg}"
			shift # past - option
			;;
		-w|--wlist)
			arg=$((i+1))
			WORDLIST="${!arg}"
			shift # past - option
			;;
		# did the user ask for help?
		-h|--help)
			display_usage
			exit 0
			;;
		*)
			display_usage
			exit 0
			;;
	esac
done

# did the user supply the IP or the file?
if [ "$OPTION" -eq "0"  ]; then
	display_usage
	exit 0
else
	case "$OPTION" in
		"1")
			read_file_and_scan
			wait_for_completion
			;;
		"2")
			# is the IP address proper?
			check_ip $IP
			# sweep the IP address given
			ping_sweep $IP
			# wait for all of the spawned processes to finish
			wait
			read_file_and_scan
			wait_for_completion
			;;
		"3")
			# single IP
			check_ip_full $IP
			if [ $? -eq 0 ]; then 
				scans $IP
				wait_for_completion
			else
				exit 0
			fi
			;;
	
	esac
	
fi
